### ISSUE TITLE
Danger : committing .env files

### ISSUE THREAD

**Issue by PapiHack** [kheuch2018/ayweustore#1]
Hello @kheuch2018, i hope you're doing well.

I just saw your awesome project.
However I noticed that you have committed your `.env` files for `dev` and `prod`. Which can be quite dangerous if it contains sensitive informations.
I don't know if it's an oversight or an omission but best practices recommends to rather add this file in your `.gitignore` and create an example template file named `.env.example` with your environment variables as a doc for those, like this :

```
NEXT_PUBLIC_ENDPOINT_URL=  
NEXT_PUBLIC_CLOUDFRONT_IMG_URL=  
NEXT_PUBLIC_CLOUDFRONT_ENDPOINT_URL=
```
Sorry for the inconvenience.
Nice UI by the way! #aywa #gnouDiay :)

**Comment by kheuch2018** [comment]
Hello @PapiHack  
thanks for the remark. It's very useful

Haha... Btw I made this project public by error. 

you saved my life

What I'll do Next:
- make this repo private
- remove these informations from the .env 

 Hopefully they're not sooo sensitive
 
 Thanks again
